newsapi:
  baseurl_1: ${NEWSAPI_BASEURL:https://newsapi.org/v2/top-headlines}
  cost_1: ${NEWSAPI_COST:5.50}
  apikey_1: ${NEWSAPI_KEY:#########}
  baseurl_2: ${NEWSIO_BASEURL:https://newsdata.io/api/1/news}
  cost_2: ${NEWSIO_COST:4.50}
  apikey_2: ${NEWSIO_KEY:###########}

jwt:
  secret: ${JWT_SECRET:#########}

billing:
  everything: ${COST_EVERYTHING:10.50}
  topheadlines: ${COST_TOPHEADLINES:5.50}
  sources: ${COST_SOURCES:200}

spring:
  datasource:
    url: ${DATASOURCE_URL:jdbc:postgresql://localhost:5432/newsApi}
    username: ${DATASOURCE_USERNAME:#########}
    password: ${DATASOURCE_PASSWORD:#######}
  jpa:
    hibernate:
      ddl-auto: update
  thymeleaf:
    cache: false
    prefix: classpath:/templates/
    suffix: .html
    encoding: UTF-8
    mode: HTML
    baseurl: ${APP_BASEURL:http://localhost:8080/}
  mail:
    host: smtp.gmail.com
    port: 587
    username: ${GMAIL_USERNAME:#####}
    password: ${GMAIL_PASSWORD:#####}
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true

management:
  server:
    port: 4003
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    prometheus:
      enabled: true
  metrics:
    web:
      server:
        request:
          autotime:
            enabled: true
    export:
      prometheus:
        enabled: true
